name: Weekly Docker Security Update

on:
  schedule:
    # Run every Monday at 2:00 AM UTC
    - cron: '0 2 * * 1'
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual security update'

jobs:
  update-docker-image:
    name: Update Docker Image with Security Patches
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.lightweight
          push: true
          tags: |
            bartholemewii/stans-ml-stack:0.1.4-secure
            bartholemewii/stans-ml-stack:latest
            bartholemewii/stans-ml-stack:rocm-latest
            bartholemewii/stans-ml-stack:security-${{ steps.date.outputs.date }}
          cache-from: type=registry,ref=bartholemewii/stans-ml-stack:latest
          
      - name: Run Docker Scout
        run: |
          # Install Docker Scout if not available
          if ! command -v docker-scout &> /dev/null; then
            echo "Installing Docker Scout..."
            curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --
          fi
          
          # Analyze the image for vulnerabilities
          docker scout cves bartholemewii/stans-ml-stack:latest --format sarif > security-report.sarif
          docker scout cves bartholemewii/stans-ml-stack:latest --format markdown > security-report.md
          
      - name: Create security summary
        run: |
          echo "# Docker Security Update - ${{ steps.date.outputs.date }}" > security-summary.md
          echo "" >> security-summary.md
          echo "## Changes Applied" >> security-summary.md
          echo "- Updated base image to latest ROCm version" >> security-summary.md
          echo "- Applied system package updates" >> security-summary.md
          echo "- Updated Python dependencies with security fixes" >> security-summary.md
          echo "" >> security-summary.md
          echo "## Remaining Security Issues" >> security-summary.md
          echo "See the attached security report for details on any remaining issues." >> security-summary.md
          
          # Extract high and critical vulnerabilities for the summary
          echo "" >> security-summary.md
          echo "### High and Critical Vulnerabilities" >> security-summary.md
          grep -A 5 "high\|critical" security-report.md >> security-summary.md || echo "No high or critical vulnerabilities found." >> security-summary.md
          
      - name: Upload security reports
        uses: actions/upload-artifact@v3
        with:
          name: security-reports-${{ steps.date.outputs.date }}
          path: |
            security-report.sarif
            security-report.md
            security-summary.md
            
      - name: Create Issue with Security Update Summary
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "Docker Security Update - ${{ steps.date.outputs.date }}"
          content-filepath: ./security-summary.md
          labels: security, docker, automated
          
      - name: Notify on Slack (if configured)
        if: ${{ secrets.SLACK_WEBHOOK_URL != '' }}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              "text": "Docker Security Update Completed",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Docker Security Update - ${{ steps.date.outputs.date }}*\nThe weekly security update for Stan's ML Stack Docker image has been completed. See the GitHub issue for details."
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        continue-on-error: true
